# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  pre-build:
    runs-on: ubuntu-latest

    steps:
      - name: send Pre-Message
        run: curl --location --request POST '122.128.169.32:8080/choi' --form 'message="Job[$GITHUB_RUN_ID] Repo[$GITHUB_REPOSITORY] GitHub 에 정상적으로 등록되어 CI/CD 가 실행중입니다"'

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: The job has successed
      if: ${{ success() }}
      run: curl --location --request POST '122.128.169.32:8080/choi' --form 'message="Job[$GITHUB_RUN_ID] Repo[$GITHUB_REPOSITORY] 빌드에 성공하였습니다!"'

    - name: Then job has Failed
      if: ${{ !success() }}
      run: curl --location --request POST '122.128.169.32:8080/choi' --form 'message="Job[$GITHUB_RUN_ID] Repo[$GITHUB_REPOSITORY] 빌드에 실패하였습니다 코드를 확인해주세요!"'

